CREATE SCHEMA AS_DC;

CREATE SEQUENCE AS_DC.AS_GENERIC_SEQ
    START WITH 50002
    INCREMENT BY 1;

CREATE TABLE AS_DC.ACCOUNT_TYPE
(
    ACCOUNT_TYPE_ID BIGINT      NOT NULL,
    MNEMONIC        VARCHAR(100) NOT NULL UNIQUE,
    ACCOUNT_TYPE_NAME            VARCHAR(255) NOT NULL,
    CREATION_DATE       DATE    NOT NULL,
    PRIMARY KEY (ACCOUNT_TYPE_ID)
);

CREATE TABLE AS_DC.ACCOUNT_TYPE_TX
(
    TRANSC_ID   BIGINT      NOT NULL,
    ACCOUNT_TYPE_ID BIGINT      NOT NULL,
    MEMBER_ID   BIGINT,
    AMOUNT  BIGINT      NOT NULL,
    TRANSC_DATE      DATE    NOT NULL,
    PRIMARY KEY (TRANSC_ID),
    CONSTRAINT FK_ACCOUNT_TYPE_ID FOREIGN KEY (ACCOUNT_TYPE_ID) REFERENCES AS_DC.DC_ACCOUNT_TYPE (ACCOUNT_TYPE_ID),
);